### PR TITLE
Fix Chinese & Japanese space issue

### LINKED ISSUE #16: Avoid spaces between words in Japanese and Chinese
Thank you for the development efforts! The app runs rather well for these languages, but neither of them adds spaces between words. It would be great if the keyboard skips adding spaces for these languages.

### PR DESCRIPTION
**Pull request by moonbeamcelery**
Trying to close #16 myself.
Passing locale to filter out whitespaces in languages where they are irrelevant.

### CODE REVIEW

**Comment by ElishaAz** [comment]
Thanks for the contribution!

A few things: 
1. Is there a chance that someone will want the spaces?
2. The line `text = text.replace("\\s".toRegex(), "")` should be called inside `VoskLocal` (and `VoskServer`) as it's specific to that source (it shouldn't have placed the spaces in the first place)
3. In `shouldAddSpace`, it's better to return before ` val cs = ic.getTextBeforeCursor(1, 0)`, as it's an expensive call

I can make the changes myself if you prefer

**Comment by moonbeamcelery** [comment]
I can make those changes!
1. I can't say for sure for Japanese, but for Chinese there's no use case that needs those spaces between words. I don't understand why vosk adds them.

**Comment by moonbeamcelery** [comment]
Made required changes.

**Comment by moonbeamcelery** [comment]
While I have your attention. I'm thinking of implementing 29, but with trigger words to switch between them, like when you say "spelling mode" and pause, the app instead of committing the text, it calls [this thing](https://github.com/alphacep/vosk-api/blob/master/kotlin/src/commonMain/kotlin/org/vosk/Recognizer.kt#L104). What do you think?

There could be a list of phrases and the corresponding punctuation and character. I can hard-code it first and see where you want to put it.

**Pull request merged**
